# Generated by Django 4.2.7 on 2025-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='hospital_clinic',
            field=models.CharField(blank=True, help_text='Legacy field - use hospitals relationship instead', max_length=200),
        ),
    ]
