# Generated by Django 4.2.7 on 2025-08-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_healthcareprovider_hospitals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Tell us about your specific IoT monitoring needs or any questions'),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='license_document',
            field=models.FileField(blank=True, help_text='Upload license document for verification', null=True, upload_to='license_documents/'),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='organization_facility',
            field=models.CharField(default='Not Specified', help_text='Organization/Facility (General Hospital, Private Practice, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='professional_role',
            field=models.CharField(choices=[('Physician', 'Physician'), ('Registered Nurse', 'Registered Nurse'), ('Specialist', 'Specialist'), ('Healthcare Administrator', 'Healthcare Administrator'), ('Medical Technician', 'Medical Technician'), ('Other', 'Other')], default='Other', help_text='Primary professional role', max_length=50),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='professional_title',
            field=models.CharField(choices=[('Dr.', 'Dr. (Doctor)'), ('Prof.', 'Prof. (Professor)'), ('RN', 'RN (Registered Nurse)'), ('LPN', 'LPN (Licensed Practical Nurse)'), ('NP', 'NP (Nurse Practitioner)'), ('PA', 'PA (Physician Assistant)'), ('RPh', 'RPh (Pharmacist)'), ('PT', 'PT (Physical Therapist)'), ('OT', 'OT (Occupational Therapist)'), ('RT', 'RT (Respiratory Therapist)'), ('MT', 'MT (Medical Technologist)'), ('RD', 'RD (Registered Dietitian)'), ('MSW', 'MSW (Medical Social Worker)'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default='Dr.', help_text='Professional title (Dr., RN, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='hospital_clinic',
            field=models.CharField(blank=True, help_text='Legacy field - use organization_facility instead', max_length=200),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='license_number',
            field=models.CharField(help_text='Professional license number for verification', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
