# Generated by Django 4.2.7 on 2025-09-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_healthcareprovider_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='license_verified',
        ),
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='organization_facility',
        ),
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='professional_role',
        ),
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='professional_title',
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='hospital_clinic',
            field=models.CharField(blank=True, help_text='Legacy field - use hospitals relationship instead', max_length=200),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
