# Generated by Django 4.2.7 on 2025-08-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_path',
            field=models.CharField(blank=True, help_text='Stores the path of the uploaded profile image.', max_length=255, null=True, verbose_name='profile image path'),
        ),
    ]
