# Generated by Django 4.2.7 on 2025-08-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_healthcareprovider_hospitals_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='healthcare_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='providers.healthcareprovider'),
        ),
        migrations.DeleteModel(
            name='HealthcareProvider',
        ),
    ]
