# Generated by Django 4.2.7 on 2025-08-06 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('hospital_type', models.CharField(choices=[('public', 'Public Hospital'), ('private', 'Private Hospital'), ('clinic', 'Private Clinic'), ('specialized', 'Specialized Center'), ('military', 'Military Hospital'), ('university', 'University Hospital'), ('community', 'Community Health Center')], default='private', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the hospital')),
                ('specialties', models.TextField(blank=True, help_text='Comma-separated list of specialties offered')),
                ('facilities', models.TextField(blank=True, help_text='Available facilities (ICU, Emergency, etc.)')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bed_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('emergency_services', models.BooleanField(default=False)),
                ('appointment_booking_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'region'], name='hospitals_city_33ea77_idx'), models.Index(fields=['hospital_type'], name='hospitals_hospita_2fee4a_idx'), models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx')],
            },
        ),
    ]
